name = "corgi-au"
main = "src/index.ts"
compatibility_date = "2026-09-01"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "corgi-au"
database_id = "e9d74c30-49d8-4ea3-9402-d3327368a145"

[triggers]
crons = ["0 2 * * *"]
